### ISSUE TITLE
Create presentation to teach team about Ephemeral Cluster 

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/devops#10]
The `Ephemeral Cluster` which will eventually live [here](https://github.com/celestiaorg/ephemeral-cluster) but for now lives [here](https://github.com/celestiaorg/devops-test) can be a valuable tool for the entire engineering team. However, it will only be useful if all engineers feel comfortable using it and don't feel like it is requiring significant mental bandwidth to use. 

To resolve this I am going to put together a presentation consisting of a short slide show (mostly to show the architecture) as well as a live demo to demonstrate some ways different teams could utilize the cluster for their Software Development Lifecycle (SDLC).

**Comment by liamsi** [comment]
can this issue be closed?
