### ISSUE TITLE
Ensure that CHANGELOG.md file exists and is updated on PR merges to master

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/devops#17]
There should be an automated step that ensures that a CHANGELOG.md file is appropriately updated for all merges to the main branch of all `celestiaorg` code repositories. 

- [x] https://github.com/celestiaorg/celestia-node/issues/246
- [x] https://github.com/celestiaorg/lazyledger-app/issues/155
- [x] https://github.com/celestiaorg/optimint/issues/197
- [x] https://github.com/celestiaorg/celestia-core/issues/588
- [x] https://github.com/celestiaorg/smt/issues/65
- [x] https://github.com/celestiaorg/dalc/issues/20
- [x] https://github.com/celestiaorg/nmt/issues/52
- [x] https://github.com/celestiaorg/rsmt2d/issues/62

**Comment by jbowen93** [comment]
Related [devops-test](https://github.com/celestiaorg/devops-test) issues:

- [ ] https://github.com/celestiaorg/devops-test/issues/26

**Comment by liamsi** [comment]
Closing as all boxes are ticked above 🚀
