### ISSUE TITLE
Document the new state of container images of Rollkit

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#170]
https://www.notion.so/celestiaorg/Container-b7b0e9676c15494a8ee0ba35a7fcb07a
Dependabot section: https://www.notion.so/celestiaorg/CI-CD-aff2c46af37e47efa472ef37c8805bf9?pvs=4#cd624a6ca0104c1681ac9a7d0cd5db86

Closes https://github.com/celestiaorg/devops/issues/115

**Comment by Bidon15** [comment]
I approve the docs as is bc we just kick-start the whole process. 
Who does need to approve this in order to get the EPIC done @smuu ? the entire @celestiaorg/devops and @nashqueue ?
