### ISSUE TITLE
local-celestia-devnet releases for different networks

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#174]
local-devnet should have versioned releases

mocha, arabica, and BSR -> maybe use different branches

make use of Dependabot

**Comment by smuu** [comment]
@Bidon15 Is it enough to have `local-celestia-devnet` tagged with the `node` version? Or does this still have some compatibility issues when running against different networks?

**Comment by Bidon15** [comment]
> @Bidon15 Is it enough to have `local-celestia-devnet` tagged with the `node` version? Or does this still have some compatibility issues when running against different networks?

Yeah. For the time being, tagging with node version is the best and simple option. 
Re compat -> we don't need to worry about that as devX should be the same as node is dictating
