### ISSUE TITLE
Grafana Users

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#188]
generate users via code/api

**Comment by jrmanes** [comment]
update: 

currently, we cannot use the Grafana SSO, because we are using the grafana operator: [docs](https://grafana-operator.github.io/grafana-operator/docs/examples/oauth_proxy/readme/)

**Comment by jrmanes** [comment]
script to generate the users:
[grafana_users.py](https://github.com/celestiaorg/celestia-internal-tools/blob/main/scripts/grafana_users.py)

**Comment by jrmanes** [comment]
update:
*pending to send the link to the devs, today most of them are OOO*

**Comment by smuu** [comment]
> update:
> 
> currently, we cannot use the Grafana SSO, because we are using the grafana operator: [docs](https://grafana-operator.github.io/grafana-operator/docs/examples/oauth_proxy/readme/)

In this case, we should consider not using the Grafana Operator anymore. wdyt?

**Comment by jrmanes** [comment]
> 

I agree, it seems that the operator has some limitations, SSO is not a blocker, but I find it very useful for the whole company... so we might reserve a time in the future to change it

**Comment by jrmanes** [comment]
update:

we'll review Grafana Cloud, we have to check if we can easily send the data to it, review the data sources and label the different clusters by id.
