### ISSUE TITLE
Update robusta-1 Kubernetes Cluster to 1.26.2

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#198]
The cluster is currently running on 1.26.0.

Watch how nodes are restarting and how robusta is behaving. Is a rolling update of nodes possible without downtime?

**Comment by smuu** [comment]
- pod annotation that eg. two bridges are not running on the same node
- currently only one validator, so downtime if it get's rescheduled

**Comment by jrmanes** [comment]
update:

The cluster is currently running on `v1.26.1`

**Comment by jrmanes** [comment]
pending to create the PR with the TF changes

**Comment by jrmanes** [comment]
done here: https://github.com/celestiaorg/terraform-k8s/pull/9

**Comment by jrmanes** [comment]
update: 

the nodes are being updated one by one, it doesn't matter if we have multiple node pools, k8s treats them as one
