### ISSUE TITLE
Introduce versioning to stack-internal

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#200]
Now that Arabica will use the stack-internal, we should consider using tagged versions of our Kubernetes manifests to ensure stability and avoid mistakes when changing manifests. Arabica is front-facing to users, so it should be stable and avoidable downtime should be as minimal as possible.
IMHO, this should be done before Mocha moves to stack-internal.

@sysrex We had a chat about this. You may want to add something.
@Bidon15 I will add this to the next sprint. Feel free to move it.

**Comment by Bidon15** [comment]
Closing as done 
https://github.com/celestiaorg/celestia-stack-internal/releases/tag/v0.1.0-arabica

Refactoring of stack repo from @jrmanes should be considered a full proper release once the PR(s) is(are) merged
