### ISSUE TITLE
Push with git SHA everytime `reusable_dockerfile_pipeline.yml` get's triggered

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#218]
To test versions on branches and PRs, it would be nice to have git SHA-tagged images in the container registry. As we build it every time, we can push on the git SHA every time.

As this would clutter the container registry, we would need a cron job, that cleans up old SHA tags that are not needed anymore.

**Comment by smuu** [comment]
Not really needed

**Comment by smuu** [comment]
Not really needed

**Comment by Bidon15** [comment]
We have the sha-s in node and app already
