### ISSUE TITLE
feat: approve automatically new SHA for robusta-nightly

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#235]
Hellooo!

Find the best way to approve automatically new SHA for robusta-nightly.
We should not be approving the PRs everyday manually, only for this environment

**Comment by smuu** [comment]
Random thought: Do we need GitOps for nightly? Or is it okay to deploy directly from a GitHub Workflow?

**Comment by jrmanes** [comment]
> Random thought: Do we need GitOps for nightly? Or is it okay to deploy directly from a GitHub Workflow?

I think we need it, just because for creating the nightly environments, I've configured them with the [AutoDevOps](https://github.com/celestiaorg/celestia-sre/actions/workflows/auto_devops_chain.yml) and ArgoCD, so we'll need to keep the files updates in the repo, if we deploy directly, ArgoCD will sync them and replace them.

what do you think?

**Comment by smuu** [comment]
> > Random thought: Do we need GitOps for nightly? Or is it okay to deploy directly from a GitHub Workflow?
> 
> I think we need it, just because for creating the nightly environments, I've configured them with the [AutoDevOps](https://github.com/celestiaorg/celestia-sre/actions/workflows/auto_devops_chain.yml) and ArgoCD, so we'll need to keep the files updates in the repo, if we deploy directly, ArgoCD will sync them and replace them.
> 
> what do you think?

Why does ArgoCD replace the resources? I assumed robusta-nighty would get a separate namespace. We have just no ArgoCD Application that points to that namespace or the resources.
I think that creating a workflow with auto-merging PRs is an overhead for ephemeral cluster.

**Comment by jrmanes** [comment]
*we won't follow the GitOps in that case, so we don't need this ticket anymore*
