### ISSUE TITLE
docs: robusta-nightly

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#262]
Hello team!

ℹ  *Low priority, no rush please!*

I've created this page in Notion about our environments, and I've added some notes about Robusta/Robusta-nighlty.
here: https://www.notion.so/celestiaorg/Environments-c284ba62ab314b1bb98f124a2cac0a4e

If you have some spare time, I'd appreciate any feedback 😊 

Thanks in advance! 🚀 

Jose Ramon Mañes

**Comment by smuu** [comment]
Great documentation 🚀 Just fixed some typos.

**Comment by jrmanes** [comment]
> Excellent documentation 🚀 I just fixed some typos.

thanks for taking time 😊

**Comment by Bidon15** [comment]
LGTM to me. 🚢
