### ISSUE TITLE
[EPIC]: QGB Integration into testnets

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#269]
Introduction 🧐 
---

QGB is a one way bridge that allows rollups to settle on ETH, while having Celestia as a DA Layer

In order to achieve this, QGB is divided into 3 components: 

1. Orchestrator 
2. Relayer 
3. Smart Contract in EVM chain

Orchestrator 🥁 
---

An orchestrator is run on every validator in order to sign attestations 
Every validator needs to store the private key of the EVM address that is pointed in the node settings: 
```
celestia-appd tx staking edit-validator --evm-address=<new_evm_address> --from=<validator_account> --fees 210utia
```

If we have more than 1+ validators in the chain, we need a bootstrapper to be deployed in order for the orchestrators to find one another and a relayer. As QGB forms its own p2p network. 
For PoA, we can simply add the orchestrator as a bootstrapper for the relayer

Relayer 🎹 
---

A relayer is run separately from the orchestrators/validators set. The purpose of the relayer is to gather attestations and send to the EVM chain's smart contract. In order to send attestations to the EVM chain, a relayer needs its own EVM account

Good to know 📝 
---

- Funded EVM accounts for **validators/orchestrators is not needed**
- EVM address for a **relayer needs to be funded**
- **_1 EVM address can be used for N amount of relayers_**. Meaning that 1 EVM Address can be used for robusta/arabica 
- 1 Smart Contract per testnet for QGB 
- Sepolia ETH has no API endpoint to fund the relayer (will be some manual labour as I see) 
- orchestrator and relayer use 1 dockerImage

Robusta/Arabica
---

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/devops/issues/270
- [ ] https://github.com/celestiaorg/devops/issues/271
- [ ] https://github.com/celestiaorg/devops/issues/272
- [ ] https://github.com/celestiaorg/devops/issues/273
```

**Comment by Bidon15** [comment]
Ref: https://developers.scaleway.com/en/products/secret_manager/api/v1alpha1/#quickstart

**Comment by jrmanes** [comment]
> Ref: https://developers.scaleway.com/en/products/secret_manager/api/v1alpha1/#quickstart

Hey @Bidon15
thanks for sharing this one, looks like a simple option to go, I have an epic about SecretManagement, tho if you need something now, it looks okay 👌 
Remember that for the token, we have already a secret in the namespaces (robusta-X) called: `scw-config` that you could reuse for this use case.

if you need to get the value of the secret, you can use something like:
```bash
kubectl -n <namespace> get secret scw-config -o jsonpath='{.data.SCW_ACCESS_KEY}'|base64 -d
```

**Comment by Bidon15** [comment]
Done
