### ISSUE TITLE
Find the simple secret key management for the EVM address that will be on relayers behalf

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#272]

**Comment by jrmanes** [comment]
I think we can close this one, as we're gonna go with 1pass, we can continue with all the other tasks in the [EPIC](https://github.com/celestiaorg/devops/issues/133) 👀

**Comment by jrmanes** [comment]
we can do this one using 1Pass already 🚀  
ping me when you'll be able to check it and we can do it easily 😉
