### ISSUE TITLE
Create Devnet DA Network Bootstrap Peers

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/devops#28]
The Celestia Devnet needs Celestia Node bootstrap peers to allow for individuals to run nodes in the DA halo network.

**Comment by jbowen93** [comment]
Initial lazy approach while be to create 2 Digital Ocean droplets in different regions (NYC1 and AMS3), each will run the `celestia-node` binary and sync with one of the existing validators that we run. I'll then put a loadbalancer in front of the 2 droplets and work with Mustafa to give them a domain name.

**Comment by jbowen93** [comment]
Digital Ocean doesn't support multi region load balancers so we might as well just point each sub domain at a single VM.

**Comment by jbowen93** [comment]
Currently have 3 `celestia-node`s running with `bootstrapper=true` that are synced to head. 

- `celestia-node-bootstrapper-lon1-0` (46.101.42.40)
- `celestia-node-bootstrapper-ams3-0` (164.92.215.180)
- `celestia-node-bootstrapper-nyc1-0` (192.81.208.113)

**Comment by SweeXordious** [comment]
> Digital Ocean doesn't support multi region load balancers so we might as well just point each sub domain at a single VM.

Why not just use nginx for load balancing ?
