### ISSUE TITLE
metrics: version can`t be added in metrics

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/devops#295]
Currently, `celestia-node` node's info looks like:
`{instance="12D3KooWABWnXHt5Ek1QMNA864HQffwCWkeq3iGEwxGX2mj9FRin", job="Celestia-Light/semver-v0.9.2-5-g7f556f06"}`

Where:
* instance is peerID;
* job is NodeType + semantic version;

This info is added to all metrics that we have in `celestia-node`.  To pass the build info we are using attributes(key-val). So, we are using:
1) ServiceInstanceIDKey for the peerID;
2) ServiceNamespaceKey for the Node type;
3) ServiceNameKey for the semantic versioning;

But there is one more useful constant - [ServiceVersionKey](https://github.com/open-telemetry/opentelemetry-go/blob/1b04bbc681f769b5ac6b7189e25b2790a8363c83/semconv/v1.11.0/resource.go#L898) that can be used to pass the version. From the `celestia-node` I tried several approaches to enable this field in the final view, but they did not help and the version was not printed. It will be very helpful if we can enable this file, so the final view will look like this:
`{instance="12D3KooWABWnXHt5Ek1QMNA864HQffwCWkeq3iGEwxGX2mj9FRin", job="Celestia-Light",version="v0.9.2-5-g7f556f06"}`

**Comment by smuu** [comment]
done
