### ISSUE TITLE
cicd: bug with forks

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#326]
## Description 📜

Hello team,

As you may know, in our common Docker pipeline, we are building and pushing all the commits in the step: [Build and Push Docker Image (amd64)](https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_dockerfile_pipeline.yml#L137-L147)

The problem is that when working with forks, the forks are trying to push as well, and Github is blocking them (Github security works in that way).

We need to find a way to fix that, the CI is reporting failures even if they are okay.

*More info: [slack](https://celestia-team.slack.com/archives/C02PEA73QM6/p1686215148162469)*

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

cc: @smuu

--- 

### Some interesting examples 🔍

- [orchestrator-relayer](https://github.com/celestiaorg/orchestrator-relayer/actions/runs/5211735457/jobs/9404482996)
- *Same for celestia-app*

--- 

### Tasks 🔖

- [ ] Find a way to fix that issue and solve the problem with forks
  - [*Maybe add a validation like, if coming from a fork...*

--- 

### Repository 🗂️

- [celestiaorg/.github](https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_dockerfile_pipeline.yml)

---

#### Issues 👨‍🔧

Closes: 

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by rootulp** [comment]
Note: all PRs in celestia-app from forks will fail CI until this issue is resolved. Is it possible to revert to the previous behavior so that CI doesn't fail at least until a longer term solution is identified?

**Comment by MSevey** [comment]
looking at the git history of the file, we switch the `push` value from a conditional to `true` and moved and updated the conditional to an `if`. 

https://github.com/celestiaorg/.github/commit/cb19bc06c58d52fb899193f2f7d8673843efb664

we should do a quick check if reverting this fixes the issue for the teams.
