### ISSUE TITLE
docker: tagging/branching approach for the app

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#37]
Ref: #36

**Comment by Bidon15** [comment]
Let's make a final decision when @MSevey gets fully acquainted with our stack and we have a company guideline
cc: @sysrex

**Comment by jrmanes** [comment]
ℹ️ Update:

We're having issues with the repository permissions, however we've found the root of the problem and we're pending to have the right permissions/change our role in the repo.

**Comment by Bidon15** [comment]
Closing as done 
according to https://github.com/celestiaorg/celestia-app/pull/1370
