### ISSUE TITLE
docker: tagging/branching approach for the node

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#38]
Ref: #36

**Comment by Bidon15** [comment]
Let's make a final decision when @MSevey gets fully acquainted with our stack and we have a company guideline
cc: @sysrex

**Comment by jrmanes** [comment]
hello @Bidon15 ! 

For `celestia-node` , I can see that the Docker releases are being created properly (IMHO), [celestia-node packages](https://github.com/celestiaorg/celestia-node/pkgs/container/celestia-node)

We currently have:
- latest
- sha-<SHORT_SHA>
- RC in case of release

From my point of view, I suggest you to do a couple of changes:
- Remove the `sha-` prefix and keep only the `SHORT_SHA` as `celestia-app` will be soon.
- Add Trivy for the security scanner.

WDYT? 👀 

If you want to add/change anything, please let me know 🚀 

Best!

**Comment by jrmanes** [comment]
> @jrmanes Thanks for the input!
> 
> For node, there is an issue that tags is only available for v0.6.x releases but RCs(like v0.6.x-rc-N) are not available or not tagged properly in CI docker jobs.
> 
> Adding Trivy makes sense to me. As well as having core/app strategy for dockerimages implemented in the same fashion as we have in node
> What are your thoughts on these?

I missed to respond to the previous message... S: 

--- 

> For node, there is an issue that tags is only available for v0.6.x releases but RCs(like v0.6.x-rc-N) are not available or not tagged properly in CI docker jobs.

For solving the tags and keep `celesita-node` as `celestia-app` I think we can reuse the same pipeline and we'll have the same tags, also, the next step could be to move it to `.github` repo and keep it like a common Docker CI for all the repos.
There's only one difference from `celestia-node` to `celestia-app` which is that the `Dockerfile` in node is under the `docker` folder, but it's a minor issue.

--- 

> Adding Trivy makes sense to me. As well as having core/app strategy for dockerimages implemented in the same fashion as we have in node

-> Done ✅

---

ℹ️ Update: 
Also, we have the same issue with the permissions as we have in [celesita-app](https://github.com/celestiaorg/devops/issues/37#issuecomment-1415946448)
Once we solve it, we'll be able to do it in both repos.
