### ISSUE TITLE
Enabled Kubernetes Clusters integration for our deployments

### ISSUE THREAD

**Issue by sysrex** [celestiaorg/devops#398]

**Comment by jrmanes** [comment]
hello @sysrex 

I've been checking Snyk for Kubernetes, but I found that with the current plan is not possible...

This feature is only available in the [enterprise plan](https://docs.snyk.io/scan-containers/kubernetes-integration/kubernetes-integration-overview), so I think we should reconsider enabling this feature as we'll be forced to upgrade the plan...



![Image](https://github.com/celestiaorg/devops/assets/32740567/d5eb4bf5-687b-483a-8a5c-1209efe70bdf)


![Image](https://github.com/celestiaorg/devops/assets/32740567/609dcd5c-4255-4767-943a-66f98caecac0)


what do you think?

**Comment by jrmanes** [comment]
we can close this issue for now as we'll have to check the enterprise plans or any other alternative
