### ISSUE TITLE
bug: faucet evicted

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#467]
faucet issues with the resources, increase them, it needs more:

![Image](https://user-images.githubusercontent.com/32740567/259341693-86e44512-d9eb-4975-8f89-7d08dbe37dcd.png)

**Comment by smuu** [comment]
Do you know why they need more resources in large environments like (robusta-64, robusta-128, and robusta-129)?

In the end, a faucet only creates a transfer transaction, right?

**Comment by jrmanes** [comment]
> Do you know why they need more resources in large environments like (robusta-64, robusta-128, and robusta-129)?
> 
> In the end, a faucet only creates a transfer transaction, right?

In theory yes, it only does the tx, maybe is in general, it requires more resources, and not only for those environments, but I've seen this error mostly in the big envs
