### ISSUE TITLE
upgrade arabica to v0.12.0-rc6 app and upcoming v0.7.0-rc1 node

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#51]
Celestia Node to be included into forks for bootstrappers

- [x] https://github.com/celestiaorg/celestia-node/tree/d873e026194c353e48fe26fd9406237725e93c6c
- [x] https://github.com/celestiaorg/celestia-node/pull/1689
- [x] [<drop fix> PR](https://github.com/renaynay/celestia-node/tree/drop-hotfix) 

Celestia-App: 

- [x] Try out original docker image for tag v0.12.0-rc6

**Comment by sysrex** [comment]
The image for the bootstrappers is now ready at - https://hub.docker.com/repository/docker/sysrex/celestia-node/general

**Comment by sysrex** [comment]
Deployed to Arabica correctly
