### ISSUE TITLE
docker: Create Bootstraper Image

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#54]
Hello team,

We need to create a Docker image for the boostrapers, for avoiding use any workaround.

--- 

- [ ] Build Docker image as a bootstraper

--- 

Next steps:
- [ ] Once we have the common CI, add this image to the CI

--- 

##  This has to be done for the service.
- [ ] [celestia-node](https://github.com/celestiaorg/celestia-node)

---

Related tickets:

- https://github.com/celestiaorg/celestia-node/issues/63
- https://github.com/celestiaorg/celestia-node/issues/1057

--- 

Best 🚀 

Jose Ramon Mañes

**Comment by Bidon15** [comment]
Bootstrappers do not initialise when they start

Reason: 
You don't want to reinitialise an underlying data store 

More info here: 
https://github.com/celestiaorg/celestia-node/issues/1057

**Comment by Bidon15** [comment]
Build 2 diff containers: 

1. Separate bootstrapper image
2. Leave current one as is

**Comment by smuu** [comment]
celestia-node will introduce a `BOOTSTRAPPER` env variable in celestiaorg/celestia-node#1881. Therefore a separate Docker image is not needed. I will add a closed-by to the issue description.

**Comment by sysrex** [comment]
I've commented on the PR, there is no scenario in which celestia-node repo will be used for boot strapper nodes outside of our team, so I would avoid adding it there, instead we can create a different workflow for the bootstrapper which will only be used / triggered by us.

**Comment by smuu** [comment]
> I've commented on the PR, there is no scenario in which celestia-node repo will be used for boot strapper nodes outside of our team, so I would avoid adding it there, instead we can create a different workflow for the bootstrapper which will only be used / triggered by us.

I talked to Hlib, and this was the way he proposed to me to solve this. But I think it would be good to remove it from the README.

**Comment by smuu** [comment]
https://github.com/celestiaorg/celestia-node/pull/1881 is merged

When they make a new release, you must switch from the `config.toml` configuration to the environment to set up a Bootstrapper node.

cc. @sysrex @jrmanes @Bidon15
