### ISSUE TITLE
argocd: GH Tokens

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#551]
hello @MSevey !

We need you to create new tokens for our ArgoCDs, the token has to be created from the `celestia-bot` account.

We need to have one token for each environment:
- [x] Robusta
- [x] Arabica
- [x] Arabica-10
- [x] Mocha
- [x] Lunaroasis

The permissions needed are specified here: [link](https://www.notion.so/celestiaorg/ArgoCD-55f67be0293144878288368595a87f7e?pvs=4#6cb5ac8a84504bda8831088a62e39366)

Once you have the token, please add them to the `Shared` vault with a name like: `argocd-<env>` and I'll move them to the right vaults.

Cheers! 🚀

**Comment by MSevey** [comment]
<img width="248" alt="Screen Shot 2023-10-16 at 11 48 29 AM" src="https://github.com/celestiaorg/devops/assets/15232757/ca9e00e5-0f1c-4d38-bdc2-46dbadc8170c">

done
