### ISSUE TITLE
keplr: Setup infra & app that provides an RPC endpoint to Keplr

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#59]
As a crucial point in upcoming ITN and beyond, we need to setup a dedicated infrastructure and Celestia-App that exposes an RPC endpoint to Keplr team

**Comment by Bidon15** [comment]
Provide a Celestia-App in Full Node for ITN that provides a RPC endpoint for Keplr team

**Comment by sysrex** [comment]
Created endpoint and provided.
