### ISSUE TITLE
archiving repos

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#609]
Closes https://github.com/celestiaorg/devops/issues/586, closes https://github.com/celestiaorg/devops/issues/587, closes https://github.com/celestiaorg/devops/issues/588, closes https://github.com/celestiaorg/devops/issues/593

**Comment by smuu** [comment]
Repos to archive:

- https://github.com/celestiaorg/kustomize-argocd
- https://github.com/celestiaorg/ansible-roles
- https://github.com/celestiaorg/celestia-helm-charts
- https://github.com/celestiaorg/celestia-external-tools

**Comment by MSevey** [comment]
done
