### ISSUE TITLE
docs: Create a page in our docu to use signed commits

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#62]
Hello team,

Some context here, this ticket was created as a reminder, for creating a page in Notion about how to setup your computer and your Github account for using signed commits.

Also, it will be great to document that we need/require to use 2FA in Github.

--- 

Why use signed commits?

Mainly, it's recommended to use GPG keys for security reasons, this will prove the commit came from you. 
It's very easy to impersonate the identity when adding commits, so this will help us to verify who is who and the commits comes from that person.

--- 

Some interesting articles:
[GPG Generate Keys](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
[Signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

--- 

- [x] Notion page
  - [x] install GPG
  - [x] how to generate them
  - [x] add the key to github
  - [x] configure git
  - [x] signing commits
- [x] Add guide for the commands
- [x] Some screenshots will be great

--- 

Next steps:
- ~Share it in the Slack to all the teams~

--- 

Best 🚀 

Jose Ramon Mañes

**Comment by smuu** [comment]
I would propose enforcing signed commits in our owned repos and maybe rolling that out later to the whole org.

**Comment by jrmanes** [comment]
> I would propose enforcing signed commits in our owned repos and maybe rolling that out later to the whole org.

I love the idea!


cc: @Bidon15 @sysrex

**Comment by Bidon15** [comment]
We need to prep this process and present it for the onsite.
Love the initiative! 

cc: @liamsi and @MSevey

**Comment by MSevey** [comment]
Part of this should be documenting the impact of signed commits from forks. Especially if we would enforce them. Would all forks need signed commits? Or is it ok for just the merge commit to be signed? 

Do signed commits impact our merge options? Ie squash and merge being our preferred? 

These should be answered in the docs 👍🏼

**Comment by smuu** [comment]
I started a notion page regarding security for another topic. I would propose working on a shared page/page structure.
https://www.notion.so/celestiaorg/Security-Best-practices-66c01715bd1247beade862cdf1d5ab89

Maybe in the beginning it lives in DevOps/Testing and later we can move it out.

**Comment by jrmanes** [comment]
I've documented the steps here: [link](https://www.notion.so/celestiaorg/Signed-Commits-45ba7a1e1e9f4dedb466ec42547e5034)
