### ISSUE TITLE
Upgrade consensus nodes on mocha-4 to celestia-app v1.3.0

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/devops#639]
## Context

<img width="852" alt="Screenshot 2023-11-21 at 10 12 37 AM" src="https://github.com/celestiaorg/devops/assets/3699047/be6bf019-ef63-4065-998b-c58da40a3675">

Ref: https://celestia.grafana.net/public-dashboards/5d14d96e44f04664bb0c44267e5d645c?orgId=1&refresh=5s

## Problem

mocha-4 is running consensus nodes on celestia-app v1.1.0. Mainnet is running celestia-app v1.3.0.

## Proposal

Upgrade consensus nodes on mocha-4 to celestia-app v1.3.0

**Comment by Bidon15** [comment]
Done 👍
