### ISSUE TITLE
networks/bot: bumping networks docs

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#64]
Currently, we have no official place in github repo where we maintain which version of the products are deployed in testnets

This needs to be implemented as a dependabot bumping main Readme.md file in celestiaorg/networks repo

**Comment by Bidon15** [comment]
Grooming 10/03/2023: 
We have some of the works done for robusta. We need to include a feature in our existing implementation for bumping a readme

Ref: #52

**Comment by rootulp** [comment]
> This needs to be implemented as a dependabot bumping main Readme.md file in celestiaorg/networks repo

I think the first version of this can be manually maintained b/c versions on Mocha, Arabica, and BSR are occasionally upgraded. The more frequent the upgrades, the stronger the motivation to automate.

**Comment by Bidon15** [comment]
Closing as networks is the original one. 
And networks issue will tracked and done with this EPIC https://github.com/celestiaorg/devops/issues/130
