### ISSUE TITLE
k8s: Improvements/Refactors various

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#68]
## Description 📜

Hello team,

The following ticket is created in order to add some improvements to our Kubernetes resources.

*Currently for the Robusta network, though the resources will be shared among the other networks in future*

Giving some context, after deploying the Robusta chain in K8S, we've realised about some improvements that we can do in our K8S platform.

If you have more in mind, please, feel free to add them to the list 📝 

Thanks in advance!

--- 

### Some interesting articles 🔍

[network-policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/)
[dynatrace - netpol](https://engineering.dynatrace.com/blog/kubernetes-security-best-practices-part-2-network-policies/)
[Synk - netpol](https://snyk.io/blog/kubernetes-network-policy-best-practices/#:~:text=Best%20practices%20for%20applying%20Kubernetes%20network%20policies&text=Only%20allow%20inter%2Dnamespace%20communication,receive%20non%2Dcluster%20network%20traffic.)
[Kyverno - Policy Manager](https://kyverno.io/)
[priority classes - 1](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/)
[priority classes -2](https://devopscube.com/pod-priorityclass-preemption/)

--- 

### Sorted by priority 🔖

ℹ️  Please, check this ticket before:

- [x] #66  

--- 

- ~[ ] Bridge should automatically restart if app ip changes (Not needed as behind a Service IP)~
- [x] Set priority Classes for the nodes (ask @smuu , @jrmanes for more info)
- [x] Check if internal DNS resolves to internal or external ip
- [x] Add probes (live, ready, and startup if required)
- [x] [non-blocking] Don't run as root
- [ ] Network policies (Check [Kyverno](https://kyverno.io/))
- [x] Set tag of alpine
- ~[ ] Enable dependabot for alpine container (and maybe later app and node)~
- [x] Kustomize Linters -> yaml
  ~- [ ] It would be great if we can have a precommit for that~

--- 

### Repository 🗂️

- [celestia-stack](https://github.com/celestiaorg/celestia-stack)

--- 

PS: *Please, feel free to update any part of the ticket, any suggestion/idea is always welcome* 😊 

---

Best 🚀 

Jose Ramon Mañes

**Comment by Bidon15** [comment]
@Bidon15 todo: 
Groom this out into smaller issues
