### ISSUE TITLE
observability: Issue with Grafana & Promtheus

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#70]
## Description 📜

Hello!

We are facing some issues with the performance in Grafana, it's very slow when getting data form Prometheus as data sources.

Kubernetes cluster: *Robusta*

Accessing: Port forwarding so far.

@smuu is aware of it, though he's gonna be flying today 🛫

Any question, idea is always welcome 😊 

Cheers!

--- 

### Some interesting articles 🔍

[port-forward k8s](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)

--- 

### Sorted by priority 🔖

- [ ] Check the problem with the performance when getting data from Prometheus to Grafana.
- [ ] Check the operator.
- [ ] Test deploying Grafana in standalone mode.

--- 

### Repository 🗂️

- [celestia-internal-tools](https://github.com/celestiaorg/celestia-internal-tools)

---

Best 🚀 

Jose Ramon Mañes

**Comment by Bidon15** [comment]
thinking more about this 
@sysrex proposed to just use Grafana Cloud 

wdyt?

**Comment by smuu** [comment]
#fixed

**Comment by smuu** [comment]
> thinking more about this @sysrex proposed to just use Grafana Cloud
> 
> wdyt?

Let's create a separate ticket about that and let's discuss!

**Comment by jrmanes** [comment]
New ticket created: https://github.com/celestiaorg/devops/issues/73

**Comment by smuu** [comment]
The issue was that the Prometheus stack has some NetworkPolicies and after allowing access from Grafana, it worked without any issues.

**Comment by jrmanes** [comment]
> The issue was that the Prometheus stack has some NetworkPolicies and after allowing access from Grafana, it worked without any issues.

huge mate! 🚀
