### ISSUE TITLE
robusta/qgb: introduction to EVM address in the validator

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#71]
Currently, we are mocking out EVM address in our validator for `robusta`
This needs to be changed, so qgb can be tested out using robusta

In order to finish this issue we need to :

- [x] change the EVM address to `0xF25AAa05FE834c2460BaE471c2237E1D3edFB589` Rachid can share the private key if neccessary
- [x] expose RPC from a `celestia-app validator / consensus node in validating mode` and give the endpoint to @SweeXordious to test

**Comment by SweeXordious** [comment]
Awesome, thanks a lot @Bidon15 

For the second part, I will need access to tendermint RPC 26657 and gRPC 9090 for the validator of the network

**Comment by Bidon15** [comment]
After we have a faucet up and running, @jrmanes please notify @SweeXordious to test out the setup with QGB 🙏 
Tracking for faucet -> will include later 😅

**Comment by SweeXordious** [comment]
Thanks a lot. I don't need faucet btw, I only nee RPC and gRPC :D

**Comment by jrmanes** [comment]
hello @SweeXordious 

the dns are the following:
```
consensus-full.celestia-robusta.com
full.consensus.celestia-robusta.com
```

You can use what you prefer :) 


please, confirm me when you can that the endpoints are working fine

thanks in advance!

**Comment by SweeXordious** [comment]
Works fine, thanks a lot @jrmanes

**Comment by jrmanes** [comment]
> Works fine, thanks a lot @jrmanes

anytime mate! 😊
