### ISSUE TITLE
testnets/explorer: deploy bigdipper 2.0 for robusta/arabica

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#72]
To our knowledge, deploying ping.pub was very cumbersome in k8s and we want to try out big dipper to see if there is any difference

https://github.com/forbole/big-dipper-2.0-cosmos

Documentation: http://docs.bigdipper.live/

**Comment by smuu** [comment]
Current state: The explorer started to support cosmos/v0.46.x only a few weeks ago. Therefore it could still be unstable.

Also, we added breaking changes to our fork of cosmos-sdk (EVM address in gentx), which needs to be supported. I'm in contact with @SweeXordious about that.

Current work:
https://github.com/smuu/forbole-juno/tree/v4.0.3-celestia
https://github.com/smuu/forbole-bdjuno/tree/chains/celestia/robusta

Once it works, I will add it to celestiaorg repos/forks cleanly.

**Comment by SweeXordious** [comment]
@cmwaters When you have time, can you take a look if it's easy to migrate the juno implementation to comet?

**Comment by Bidon15** [comment]
Can we close this as it is taking too much time?

**Comment by smuu** [comment]
We agreed with @SweeXordious not to work on this right now, as everybody is otherwise busy.
Moved to Q3.

**Comment by Bidon15** [comment]
Closing as not planned for now
