### ISSUE TITLE
k8s: DNS - external-dns

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#74]
## Description 📜

Hello team,

The following ticket is created in order to keep a track about the progress.

I've already deployed and tested that the DNS records are being working fine 👌 

Thanks in advance!

--- 

### Some interesting articles 🔍

[commit-changes](https://github.com/celestiaorg/celestia-internal-tools/commit/76a76772bdd003e9393b3289dca3bef180753c1b)

--- 

### Sorted by priority 🔖

- [x] Check the DNS resolution
- [x] Check that the ports are open
- [x] Check that the ports can be reached using the DNS

--- 

### Repository 🗂️

- [celestia-internal-tools](https://github.com/celestiaorg/celestia-internal-tools/tree/feature/robusta-tools)

---

Best 🚀 

Jose Ramon Mañes

**Comment by smuu** [comment]
Open questions from my side:
- Do we want to have one installation of external-dns per
  - cluster
  - root zone
  - project
- How can we handle multiple installations of external-dns in one cluster? Multiple instances should not update the same entry.

**Comment by jrmanes** [comment]
> Open questions from my side:
> 
> * Do we want to have one installation of external-dns per
>   
>   * cluster
>   * root zone
>   * project
> * How can we handle multiple installations of external-dns in one cluster? Multiple instances should not update the same entry.

for now, we're having small external-dns per namespaces, which the scope of them are their namespace and take care about services/ingress inside of them.

I don't rule out to change it and use one per cluster (bc the clusters are in a project, as are the dns)
