### ISSUE TITLE
create a bootstrappers' infra for ITN in diff cloud providers and regions

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#76]
We need to deploy bootstrappers' in diff regions and cloud providers with docker-compose 

8~10 boostrappers in diff regions

- [ ] GCP EU 
- [x] ScaleWay EU 
- [x] AWS/GCP Asia(South-East Asia, too)  included
- [ ] Australia? 
- [ ] LATAM?

**Comment by smuu** [comment]
Discussion about Bootstrapper Availability: https://www.notion.so/celestiaorg/Bootstrapper-Availability-87aff0206b324d66ba00ae9dbe0a29a1

**Comment by sysrex** [comment]
We created 3 of them in Scaleway EU and 1 in DO Asia for the time being.
