### ISSUE TITLE
coordination: ask app/node to comply with the process of naming release candidates

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/devops#82]
Self-explanatory

**Comment by rootulp** [comment]
What is the "process of naming release candidates"? Are `-rc0` release tags sufficient? E.g. https://github.com/celestiaorg/celestia-app/releases/tag/v0.13.0-rc0

**Comment by Bidon15** [comment]
> What is the "process of naming release candidates"? Are `-rc0` release tags sufficient? E.g. https://github.com/celestiaorg/celestia-app/releases/tag/v0.13.0-rc0

Yeah. We have been figuring out better improvements for the process. We will cover proposals in upcoming meetings with app/node teams and keep rollkit team in the loop
